### ISSUE TITLE
Seekers. При изменении имени на имя начинающееся с цифры, в дефолтной аватарке цифра прорисована дважды

### ISSUE THREAD

**Issue by dyndtikj** [VK-BMSTU-QA/homework-2-autumn-2023#28]
Приоритет: низкий
URL: https://mailbx.ru/profile
Окружение: ОС Mac OS Ventura 13.6, Браузер Google chrome 117.0.5938.149

Шаги воспроизведения:

- Зарегистрировать аккаунт 
- Перейти на страницу профиля
- Изменить имя на имя начинающееся с цифры
- Нажать кнопку сохранить

Ожидаемый результат: Аватар меняется и содержит цифру по середине
Фактический результат: Аватар меняется, но цифра прорисована дважды

<img width="543" alt="Баг_профиль_2" src="https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/81376140/923fda35-98ba-4b11-8274-36d4defcc748">

Креды для тестового аккаунта ( на нем необходимо поменять аватарку ):
Логин: testexample
Пароль: 12345

**Comment by MoraPresence** [comment]
апрув

**Comment by vvinokurshin** [comment]
- Зарегистрировать*

**Comment by vvinokurshin** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
