### ISSUE TITLE
Seekers. При пометке писем непрочианными на мобильном устройстве, пометка непрочитанности предыдущего письма увеличивается в размере

### ISSUE THREAD

**Issue by dyndtikj** [VK-BMSTU-QA/homework-2-autumn-2023#29]
Приоритет: низкий
URL: https://mailbx.ru/inbox
Окружение:
- OC Android 13, Google Chrome 117.0.5938.153
- ОС Mac OS Ventura 13.6, Браузер Google chrome 117.0.5938.149

Шаги воспроизведения:

- Авторизоваться
- Написать 2 письма самому себе 
- Зайти в папку исходящие
- По очереди помечать письма непрочитанными

Ожидаемый результат: При пометке меняется статус текущего письма, состояние других писем не меняется
Фактический результат: При пометке меняется статус текущего письма и меняется отображение знака непрочитанности предыдщего письма ( увеличивается в размере )

Десктоп:
<img width="1512" alt="image" src="https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/81376140/f96fab59-b3ef-4ee1-94fb-a66f492efcc8">

Мобилки:
![Без названия](https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/81376140/550a342d-e60e-41d7-94fb-79e8d22733ba)

Креды для тестового аккаунта:
Логин: test
Пароль: 12345

**Comment by MoraPresence** [comment]
апрув

**Comment by vvinokurshin** [comment]
- Зайти в исходящие или во входящие? На скрине одно, в тексте другое

**Comment by vvinokurshin** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
