### ISSUE TITLE
Seekers. При выборе форматирования при написании письма слетает курсор с текущей позиции

### ISSUE THREAD

**Issue by dyndtikj** [VK-BMSTU-QA/homework-2-autumn-2023#30]
Приоритет: высокий
URL: https://mailbx.ru/
Окружение: ОС Mac OS Ventura 13.6, Браузер Google chrome 117.0.5938.149
Шаги воспроизведения:

- Авторизоваться
- Нажать на кнопку "Новое письмо"
- Написать часть текста
- Выбрать форматирование ( например жирный текст )
- Продолжить вводить текст

Ожидаемый результат: При продолжении ввода будет введен жирный текст
Фактический результат: Текст не будет введет, так как  у курсора пропал фокус и необходимо в ручную заново проставлять курсор.

Подтверждение:

До выбора форматирования курсор на текущей позиции
![До_форматирования](https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/81376140/c649ec24-fa48-4dae-b932-ca9762c6a57c)

После выбора форматирования курсор слетел
![После_выбора_форматирования](https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/81376140/be7c35bb-f77c-4bf2-8be1-0b45f7a8e28d)

Креды для тестового аккаунта:
Логин: test
Пароль: 12345

**Comment by MoraPresence** [comment]
апрув

**Comment by vvinokurshin** [comment]
- В ожидаемом результате слово "будет" дублируется
- Лучше видос приложить, чем скрины, я думаю

**Comment by vvinokurshin** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
