### ISSUE TITLE
Seekers. Мало действий при нажатии на кнопку "Фильтр"

### ISSUE THREAD

**Issue by MoraPresence** [VK-BMSTU-QA/homework-2-autumn-2023#39]
Тип задачи: Улучшение
Приоритет: низкий
URL: https://mailbx.ru/inbox
Окружение: Windows 11 Pro 22621.2361 Google Chrome Версия 117.0.5938.134

Шаги воспроизведения:

   1. Зарегистрировать аккаунт
   2. Перейти на страницу писем
   3. Нажать на кнопку "Фильтр"

**Ожидаемый результат**: Сортировка писем по дате/сортировка писем по прочитанным/сортировка писем по вложениям
**Фактический результат**: Сортировка писем по дате
![image](https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/54858588/d554ccc3-9045-4f70-a778-fd127de38c66)

Креды для тестового аккаунта:
Логин: test
Пароль: 12345

**Comment by vvinokurshin** [comment]
- Зарегистрировать*
- В шаги лучше ссылку тоже добавить

**Comment by vvinokurshin** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
