### ISSUE TITLE
Seekers. При удалении папки пользователь не видит, что письма будут перемещены в корзину

### ISSUE THREAD

**Issue by MoraPresence** [VK-BMSTU-QA/homework-2-autumn-2023#40]
Приоритет: низкий
URL: https://mailbx.ru/inbox
Окружение: Windows 11 Pro 22621.2361 Google Chrome Версия 117.0.5938.134

Шаги воспроизведения:

   1. Зарегистрировать аккаунт
   2. Перейти на страницу писем
   3. Кликнуть правой кнопкой мышки на любую из созданных папок пользователем
   4. Нажать кнопку "Удалить" в всплывающем окне

**Ожидаемый результат**: Всплывает окно с подтверждением удаления папки и уведомлением, что все письма будут перемещены в папку "Корзина"
**Фактический результат**: Папка просто удаляется

Креды для тестового аккаунта:
Логин: test
Пароль: 12345

**Comment by vvinokurshin** [comment]
- Зарегистрировать*

**Comment by vvinokurshin** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
