### ISSUE TITLE
Seekers. При вводе пароля отсутствует возможность скрытия содержимого

### ISSUE THREAD

**Issue by MoraPresence** [VK-BMSTU-QA/homework-2-autumn-2023#41]
Приоритет: средний
URL: https://mailbx.ru/security
Окружение: Windows 11 Pro 22621.2361 Google Chrome Версия 117.0.5938.134

Шаги воспроизведения:

   1. Зарегистрировать аккаунт
   2. Перейти на страницу профиля
   3. Кликнуть кнопку "Пароль и безопасность"
   4. Ввести данные

**Ожидаемый результат**: Вводимые данные скрыты и существует кнопка, при нажатии на которую данные появляются, а при повторном нажатии скрываются
**Фактический результат**: Вводимые данные видны пользователю изначально
![image](https://github.com/VK-BMSTU-QA/homework-2-autumn-2023/assets/54858588/263ec13c-8fc7-48e8-91ee-b95d35a35c5c)

Креды для тестового аккаунта:
Логин: test
Пароль: 12345

**Comment by vvinokurshin** [comment]
- Зарегистрировать*
 - Ожидаемый результат: Вводимые данные скрыты и существует кнопка, при нажатии на которую данные появляются, а при повторном нажатии скрываются*

**Comment by vvinokurshin** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
